import React from "react";
import DataTable from "../components/shared/DataTable";

const Reports: React.FC = () => {
  const reportsData = [
    {
      id: 1,
      name: "Monthly Revenue Report",
      type: "Financial",
      generated: "2024-10-01",
      generatedBy: "John Doe",
      format: "PDF",
      size: "2.3 MB",
      downloads: 45,
      status: "Available",
    },
    {
      id: 2,
      name: "User Activity Analysis",
      type: "Analytics",
      generated: "2024-09-28",
      generatedBy: "Jane Smith",
      format: "Excel",
      size: "5.7 MB",
      downloads: 32,
      status: "Available",
    },
    {
      id: 3,
      name: "Security Audit Report",
      type: "Security",
      generated: "2024-09-25",
      generatedBy: "Mike Johnson",
      format: "PDF",
      size: "8.1 MB",
      downloads: 18,
      status: "Available",
    },
    {
      id: 4,
      name: "Performance Metrics",
      type: "Performance",
      generated: "2024-09-30",
      generatedBy: "Sarah Wilson",
      format: "CSV",
      size: "1.2 MB",
      downloads: 67,
      status: "Processing",
    },
    {
      id: 5,
      name: "Customer Satisfaction Survey",
      type: "Customer",
      generated: "2024-09-20",
      generatedBy: "David Brown",
      format: "PDF",
      size: "3.4 MB",
      downloads: 23,
      status: "Available",
    },
  ];

  const columns = [
    {
      key: "name",
      label: "Report Name",
      render: (value: string, row: any) => (
        <div>
          <p className="font-medium text-gray-900">{value}</p>
          <p className="text-sm text-gray-500">
            Generated by {row.generatedBy}
          </p>
        </div>
      ),
    },
    {
      key: "type",
      label: "Type",
      render: (value: string) => (
        <span
          className={`px-2 py-1 rounded-full text-xs font-medium ${
            value === "Financial"
              ? "bg-green-100 text-green-800"
              : value === "Analytics"
              ? "bg-blue-100 text-blue-800"
              : value === "Security"
              ? "bg-red-100 text-red-800"
              : value === "Performance"
              ? "bg-purple-100 text-purple-800"
              : "bg-orange-100 text-orange-800"
          }`}
        >
          {value}
        </span>
      ),
    },
    { key: "format", label: "Format" },
    { key: "size", label: "File Size" },
    {
      key: "downloads",
      label: "Downloads",
      render: (value: number) => value.toLocaleString(),
    },
    {
      key: "status",
      label: "Status",
      render: (value: string) => (
        <span
          className={`px-2 py-1 rounded-full text-xs font-medium ${
            value === "Available"
              ? "bg-green-100 text-green-800"
              : value === "Processing"
              ? "bg-yellow-100 text-yellow-800"
              : "bg-gray-100 text-gray-800"
          }`}
        >
          {value}
        </span>
      ),
    },
    { key: "generated", label: "Generated Date" },
  ];

  const actions = [
    {
      label: "Download",
      onClick: (row: any) => console.log("Download report:", row),
      variant: "primary" as const,
    },
    {
      label: "Preview",
      onClick: (row: any) => console.log("Preview report:", row),
      variant: "secondary" as const,
    },
    {
      label: "Delete",
      onClick: (row: any) => console.log("Delete report:", row),
      variant: "danger" as const,
    },
  ];

  return (
    <div className="p-6 space-y-6">
      {/* Reports Stats */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-gray-600">Total Reports</p>
              <p className="text-3xl font-bold text-gray-900">156</p>
            </div>
            <div className="text-2xl">📄</div>
          </div>
        </div>

        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-gray-600">This Month</p>
              <p className="text-3xl font-bold text-blue-600">23</p>
            </div>
            <div className="text-2xl">📊</div>
          </div>
        </div>

        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-gray-600">Downloads</p>
              <p className="text-3xl font-bold text-green-600">1.2k</p>
            </div>
            <div className="text-2xl">⬇️</div>
          </div>
        </div>

        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-gray-600">Processing</p>
              <p className="text-3xl font-bold text-yellow-600">4</p>
            </div>
            <div className="text-2xl">⏳</div>
          </div>
        </div>
      </div>

      {/* Report Generation */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">
            Quick Report Generation
          </h3>
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-3">
              {[
                {
                  type: "Financial",
                  icon: "💰",
                  color: "bg-green-50 hover:bg-green-100 border-green-200",
                },
                {
                  type: "Analytics",
                  icon: "📈",
                  color: "bg-blue-50 hover:bg-blue-100 border-blue-200",
                },
                {
                  type: "Security",
                  icon: "🔒",
                  color: "bg-red-50 hover:bg-red-100 border-red-200",
                },
                {
                  type: "Performance",
                  icon: "⚡",
                  color: "bg-purple-50 hover:bg-purple-100 border-purple-200",
                },
              ].map((report, index) => (
                <button
                  key={index}
                  className={`p-4 rounded-lg border-2 transition-colors ${report.color}`}
                >
                  <div className="text-2xl mb-2">{report.icon}</div>
                  <p className="text-sm font-medium text-gray-700">
                    {report.type}
                  </p>
                </button>
              ))}
            </div>
            <button className="w-full bg-blue-600 text-white py-3 rounded-lg hover:bg-blue-700 transition-colors">
              Generate Custom Report
            </button>
          </div>
        </div>

        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">
            Report Trends
          </h3>
          <div className="h-48 bg-gradient-to-br from-orange-50 to-red-50 rounded-lg flex items-center justify-center">
            <div className="text-center">
              <div className="text-3xl mb-2">📊</div>
              <p className="text-gray-600 font-medium">
                Report Generation Trends
              </p>
              <p className="text-sm text-gray-500">
                Monthly report generation statistics
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Reports Table */}
      {/* <DataTable
        title="All Reports"
        // columns={columns}
        data={reportsData}
        actions={actions}
        searchable={true}
        pagination={true}
      /> */}

      {/* Report Categories & Insights */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <h4 className="text-md font-semibold text-gray-900 mb-4">
            Popular Reports
          </h4>
          <div className="space-y-4">
            {[
              { name: "Monthly Revenue Report", downloads: 234 },
              { name: "User Activity Analysis", downloads: 189 },
              { name: "Performance Metrics", downloads: 156 },
              { name: "Security Audit Report", downloads: 134 },
              { name: "Customer Satisfaction", downloads: 98 },
            ].map((report, index) => (
              <div key={index} className="flex items-center justify-between">
                <span className="text-sm text-gray-700 truncate">
                  {report.name}
                </span>
                <span className="text-sm font-medium text-gray-900">
                  {report.downloads}
                </span>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <h4 className="text-md font-semibold text-gray-900 mb-4">
            Recent Activity
          </h4>
          <div className="space-y-4">
            {[
              {
                action: "Report generated",
                report: "Monthly Revenue Report",
                time: "2 hours ago",
              },
              {
                action: "Report downloaded",
                report: "User Activity Analysis",
                time: "4 hours ago",
              },
              {
                action: "Report scheduled",
                report: "Performance Metrics",
                time: "1 day ago",
              },
              {
                action: "Report shared",
                report: "Security Audit Report",
                time: "2 days ago",
              },
            ].map((activity, index) => (
              <div key={index} className="flex items-start space-x-3">
                <div className="w-2 h-2 bg-blue-500 rounded-full mt-2"></div>
                <div className="flex-1">
                  <p className="text-sm font-medium text-gray-900">
                    {activity.action}
                  </p>
                  <p className="text-xs text-gray-500">
                    {activity.report} • {activity.time}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-white rounded-lg border border-gray-200 p-6">
          <h4 className="text-md font-semibold text-gray-900 mb-4">
            Scheduled Reports
          </h4>
          <div className="space-y-4">
            {[
              {
                name: "Weekly Sales Summary",
                frequency: "Weekly",
                nextRun: "Tomorrow",
              },
              {
                name: "Monthly Financial Review",
                frequency: "Monthly",
                nextRun: "Oct 31",
              },
              {
                name: "Daily Performance Metrics",
                frequency: "Daily",
                nextRun: "Tonight",
              },
              {
                name: "Quarterly Audit Report",
                frequency: "Quarterly",
                nextRun: "Dec 31",
              },
            ].map((scheduled, index) => (
              <div key={index} className="space-y-1">
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium text-gray-900">
                    {scheduled.name}
                  </span>
                  <span className="text-xs text-blue-600">
                    {scheduled.nextRun}
                  </span>
                </div>
                <p className="text-xs text-gray-500">{scheduled.frequency}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Reports;
